from .views import *
from django.urls import path, include

urlpatterns = [
    # path('',start,name = 'Home'),
    path('', start, name='start'),
    path('about', about, name='about'),
    # path('create',country_page ),
    path('home', home),
    # path('base', definite),
    path('contact', contacts),
    path('definite', definite),
    path('indefinite', indefinite),
    path('signin', signin),
    path('signup', signup),
    path('country_info', get_info),
    path('climate', climate_info),
    path('languages', language_info),
    path('religion', religion_info),
    path('med', med_info),
    path('translators', trans_info),
    path('hotels', hotels_info),
    path('entertainments', entertain_info),
    path('attractions', attraction_info),
    path('restrictions', restriction_info),
    # path('f', signin),
    path('currency', currency_info),
    path('cart', CartView.as_view(), name='cart'),
    path('add-to-cart', AddToCartView.as_view(), name='add_to/-cart'),
    path('country_info/<str:title>/packets', packets),
    path('country_info/packet/<int:pk>', packet),
    path('country_info/packet/<int:pk>/result', packet_result),
    path('quiz', quiz),
    # path('accounts/', include('allauth.urls')),
]
